# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ambulance', models.CharField(max_length=255)),
                ('application_fee', models.CharField(max_length=255)),
                ('baby_care', models.CharField(max_length=255)),
                ('brand_drugs', models.CharField(max_length=255)),
                ('chiropractic', models.CharField(max_length=255)),
                ('coinsurance', models.CharField(max_length=255)),
                ('deductible', models.CharField(max_length=255)),
                ('emergency_room', models.CharField(max_length=255)),
                ('generic_drugs', models.CharField(max_length=255)),
                ('hospitalization', models.CharField(max_length=255)),
                ('hsa_eligible', models.CharField(max_length=255)),
                ('labor', models.CharField(max_length=255)),
                ('lifetime_maximum', models.CharField(max_length=255)),
                ('mail_order_drugs', models.CharField(max_length=255)),
                ('mental_health', models.CharField(max_length=255)),
                ('obgyn_exam', models.CharField(max_length=255)),
                ('oon_authorization', models.CharField(max_length=255)),
                ('oon_coinsurance', models.CharField(max_length=255)),
                ('oon_coverage', models.CharField(max_length=255)),
                ('oon_deductible', models.CharField(max_length=255)),
                ('oon_oop_limit', models.CharField(max_length=255)),
                ('oop_limit', models.CharField(max_length=255)),
                ('out_of_country', models.CharField(max_length=255)),
                ('pcp_required', models.CharField(max_length=255)),
                ('pcp_visit', models.CharField(max_length=255)),
                ('periodic_exam', models.CharField(max_length=255)),
                ('plan_type', models.CharField(max_length=255)),
                ('prenatal_office_visit', models.CharField(max_length=255)),
                ('separate_rx_deductible', models.CharField(max_length=255)),
                ('specialist_referrals_required', models.CharField(max_length=255)),
                ('specialist_visit', models.CharField(max_length=255)),
                ('specialty_drugs', models.CharField(max_length=255)),
                ('substance_abuse', models.CharField(max_length=255)),
                ('surgery', models.CharField(max_length=255)),
                ('urgent_care', models.CharField(max_length=255)),
                ('xray', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(max_length=255)),
                ('plan', models.CharField(max_length=255)),
                ('region', models.IntegerField()),
                ('age', models.IntegerField()),
                ('monthly_premium', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.IntegerField()),
                ('region', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
